# Generated by Django 4.2.27 on 2026-01-18 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HydrologyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatershedParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(help_text='Flow path length L (m)')),
                ('elevation_diff', models.FloatField(help_text='Elevation difference H (m)')),
                ('manning_n', models.FloatField(help_text="Manning's roughness coefficient n")),
                ('hydraulic_radius', models.FloatField(help_text='Hydraulic radius R (m)')),
                ('area', models.FloatField(help_text='Watershed area A (km²)')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hydrology.hydrologyproject')),
            ],
        ),
        migrations.CreateModel(
            name='UnitHydrographData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_ratios', models.JSONField(help_text='Time ratios t/Tp')),
                ('discharge_ratios', models.JSONField(help_text='Discharge ratios Q/Qp')),
                ('effective_rainfall', models.FloatField(default=10.0, help_text='Effective rainfall URe (mm)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrology.hydrologyproject')),
            ],
        ),
        migrations.CreateModel(
            name='RainfallParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curve_number', models.IntegerField(help_text='SCS Curve Number (CN)')),
                ('unit_duration', models.FloatField(help_text='Unit precipitation duration tr (hours)')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hydrology.hydrologyproject')),
            ],
        ),
        migrations.CreateModel(
            name='ComputationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity_table', models.JSONField(blank=True, help_text='Precipitation intensity table')),
                ('accumulation_table', models.JSONField(blank=True, help_text='Accumulated precipitation table')),
                ('hyetograph', models.JSONField(blank=True, help_text='Hyetograph data')),
                ('effective_rainfall', models.JSONField(blank=True, help_text='Effective rainfall data')),
                ('time_concentration', models.FloatField(blank=True, help_text='Time of concentration Tc (hours)', null=True)),
                ('unit_hydrograph', models.JSONField(blank=True, help_text='Unit hydrograph data')),
                ('outflow_hydrograph', models.JSONField(blank=True, help_text='Outflow hydrograph data')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hydrology.hydrologyproject')),
            ],
        ),
        migrations.CreateModel(
            name='HornerCoefficients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_period', models.IntegerField(help_text='Return period in years')),
                ('coefficient_a', models.FloatField(help_text='Horner coefficient a')),
                ('coefficient_b', models.FloatField(help_text='Horner coefficient b')),
                ('coefficient_c', models.FloatField(help_text='Horner coefficient c')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrology.hydrologyproject')),
            ],
            options={
                'unique_together': {('project', 'return_period')},
            },
        ),
    ]
